### ISSUE TITLE
Problème (warning) remonté dans les logs

### ISSUE THREAD

**Issue by thomasoup** [auchan-squid-game/auchan-squid-game#43]
Les logs de l'inspecteur du navigateur remonte des warnings dès le chargement de l'application.
Pour reproduire: 
- Se placer sur la branche *develop*
- Mette à jour la branche
- Faire un npm run serve
- Aller sur l'application, ouvrir l'inspecteur du navigateur et constater les warnings 

```
runtime-core.esm-bundler.js?5c40:6551 [Vue warn]: Property "showEnigmaPopup" was accessed during render but is not defined on instance. 
  at <CalendarCell id="cell-1" day="1" enable=""  ... > 
  at <Calendar> 
  at <Page shoudUserBeAuthenticated="" > 
  at <HomepageView onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>
warn @ runtime-core.esm-bundler.js?5c40:6551
``` 

![image](https://user-images.githubusercontent.com/33759638/139339747-b3f1ea87-0fde-4cfe-9a00-2d1fdcbacf11.png)

**Comment by fduquesne** [comment]
Fixer suite à l'implémentation de la gestion de la popup des enigmes.
